name: Terraform Plan
on:
  pull_request:
    branches: [main]
    # paths: ['terraform/**/*.{hcl,tf,yaml}']
defaults:
  run:
    shell: bash # Use bash shell for all run steps
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout
    steps:
      - uses: actions/checkout@v4
      - id: changed-files
        uses: tj-actions/changed-files@v44
        with:
            # dir_names_max_depth: 4
            # files: terraform/**/*
            matrix: true
    outputs:
        terraform-modified: ${{ steps.terraform-changed-files.outputs.any_changed }}
        terraform-modified-files: ${{ steps.terraform-changed-files.outputs.all_changed_and_modified_files }}
  plan:
    if: needs.changes.outputs.terraform-modified
    runs-on: ubuntu-latest
    timeout-minutes: 30 # mins. Default is 360 mins.
    needs: [changes]
    permissions:
      contents: read # To checkout
      pull-requests: write # To comment on PRs
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    strategy:
      fail-fast: false
      matrix:
        working-directory: ${{ fromJson(needs.changes.outputs.terraform-modified-files) }}
    steps:
      - uses: actions/checkout@v4
      - id: echo-pwd
        run: echo "PWD=${{ matrix.working-directory }}" >> "$GITHUB_OUTPUT"
      - run: gh pr comment "$GITHUB_HEAD_REF" --body "PWD=${PWD}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PWD: ${{ steps.echo-pwd.outputs.PWD }}
