name: Terraform Plan
on:
  pull_request:
    branches: [main]
defaults:
  run:
    shell: bash # Use bash shell for all run steps
env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: "1.11.3"
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout
    steps:
      - uses: actions/checkout@v4
      - id: changed-files
        uses: tj-actions/changed-files@v44
        with:
            files: terraform/**/*.{hcl,tf,yaml}
            matrix: true
      - name: Extract Unique Directories
        id: extract-dirs
        run: |
          if [ "$(echo "$all_changed_and_modified_files" | jq 'length')" -eq 0 ]; then
            unique_dirs='[]'
          else
            unique_dirs=$(echo "$all_changed_and_modified_files" | jq -r '.[]' | xargs -n1 dirname | sort -u | jq -R -s -c 'split("\n")[:-1]')
          fi
          echo "unique_dirs=${unique_dirs}" >> "$GITHUB_OUTPUT"
        env:
            all_changed_and_modified_files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    outputs:
        terraform-modified-dirs: ${{ steps.extract-dirs.outputs.unique_dirs }}
  plan:
    if: ${{ needs.changes.outputs.terraform-modified-dirs != '[]' && needs.changes.outputs.terraform-modified-dirs != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30 # mins. Default is 360 mins.
    needs: [changes]
    permissions:
      contents: read # To checkout
      id-token: write # To assume role
      pull-requests: write # To comment on PRs
    strategy:
      fail-fast: false
      matrix:
        working-directory: ${{ fromJson(needs.changes.outputs.terraform-modified-dirs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
        env:
          ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=$TF_VAR_BUCKET_NAME"
        env:
          TF_VAR_BUCKET_NAME: ${{ secrets.TF_VAR_BUCKET_NAME }}
        working-directory: ${{ matrix.working-directory }}
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ matrix.working-directory }}
      - name: Comment PR
        uses: borchero/terraform-plan-comment@v2
        with:
          token: ${{ github.token }}
          planfile: .planfile
  finish:
    if: ${{ always() && needs.changes.outputs.terraform-modified-dirs != '[]' && needs.changes.outputs.terraform-modified-dirs != '' }}
    runs-on: ubuntu-latest
    needs: [changes,plan]
    steps:
      - name: Check plan job status
        if: ${{ needs.plan.result != 'success' }}
        run: |
          echo "Terraform plan job did not succeed"
          exit 1
      - name: Finish
        run: echo "Finished"
