name: Terraform Plan
on:
  pull_request:
    branches: [main]
defaults:
  run:
    shell: bash # Use bash shell for all run steps
jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout
    steps:
      - uses: actions/checkout@v4
      - id: changed-files
        uses: tj-actions/changed-files@v44
        with:
            files: terraform/**/*.{hcl,tf,yaml}
            matrix: true
      - name: Extract Unique Directories
        id: extract-dirs
        run: |
          if [ "$(echo "$all_changed_and_modified_files" | jq 'length')" -eq 0 ]; then
            unique_dirs='[]'
          else
            unique_dirs=$(echo "$all_changed_and_modified_files" | jq -r '.[]' | xargs -n1 dirname | sort -u | jq -R -s -c 'split("\n")[:-1]')
          fi
          echo "unique_dirs=${unique_dirs}" >> "$GITHUB_OUTPUT"
        env:
            all_changed_and_modified_files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    outputs:
        terraform-modified-dirs: ${{ steps.extract-dirs.outputs.unique_dirs }}
  plan:
    if: ${{ needs.changes.outputs.terraform-modified-dirs != '[]' && needs.changes.outputs.terraform-modified-dirs != '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30 # mins. Default is 360 mins.
    needs: [changes]
    permissions:
      contents: read # To checkout
      pull-requests: write # To comment on PRs
    defaults:
      run:
        working-directory: ${{ fromJson(needs.changes.outputs.terraform-modified-dirs) }}
    strategy:
      fail-fast: false
      matrix:
        working-directory: ${{ fromJson(needs.changes.outputs.terraform-modified-dirs) }}
    steps:
      - uses: actions/checkout@v4
      - id: echo-pwd
        run: echo "PWD=${PWD}" >> "$GITHUB_OUTPUT"
      - run: gh pr comment "$GITHUB_HEAD_REF" --body "PWD=${PWD}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PWD: ${{ steps.echo-pwd.outputs.PWD }}
