name: Literals
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITEAL_'
        env:
          LITEAL_NULL: ${{ null }}
          LITEAL_BOOLEAN: ${{ true }}
          LITEAL_NUMBER:  ${{ 1234 }}
          LITEAL_STRING:  ${{ 'hello' }}
          LITEAL_OMIT_STRING:  world
