name: Manual hogehoge
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read # To checkout
    strategy:
      fail-fast: false
      matrix:
        working-directory: 
          - terraform/platform/service-1/development
          - terraform/platform/service-1/production
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Get Google Cloud Project ID and Google Cloud Project Number
        id: get_gcp_project_info
        run: |
            # Extract the values from variables.tf
            GCP_PROJECT_ID=$(grep -A 3 'variable "gcp_project_id"' variables.tf | grep default | awk '{print $3}' | tr -d '"')
            GCP_PROJECT_NUMBER=$(grep -A 3 'variable "gcp_project_number"' variables.tf | grep default | awk '{print $3}' | tr -d '"')
            echo "GCP_PROJECT_ID=${GCP_PROJECT_ID}" >> $GITHUB_OUTPUT
            echo "GCP_PROJECT_NUMBER=${GCP_PROJECT_NUMBER}" >> $GITHUB_OUTPUT
      - name: check GCP info
        run: |
            echo "workload_identity_provider: projects/${GCP_PROJECT_NUMBER}/locations/global/workloadIdentityPools/gh-actions/providers/hogehoge"
            echo "service_account: hogehoge-terraform@${GCP_PROJECT_ID}.iam.gserviceaccount.com"
        env:
          GCP_PROJECT_ID: ${{ steps.get_gcp_project_info.outputs.GCP_PROJECT_ID }}
          GCP_PROJECT_NUMBER: ${{ steps.get_gcp_project_info.outputs.GCP_PROJECT_NUMBER }}
